"""add check field in notifications

Revision ID: 5f7313e5e435
Revises: 85f37e6164af
Create Date: 2018-03-02 01:22:14.584102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7313e5e435'
down_revision = '85f37e6164af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'checked')
    # ### end Alembic commands ###
