"""add fields

Revision ID: 9fbfe41ce2a9
Revises: a1691597803e
Create Date: 2018-03-01 15:59:31.536136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbfe41ce2a9'
down_revision = 'a1691597803e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('avatar_hash', sa.String(length=128), nullable=True))
    op.add_column('employer', sa.Column('contacts', sa.String(length=500), nullable=True))
    op.add_column('employer', sa.Column('description', sa.String(length=1500), nullable=True))
    op.add_column('student', sa.Column('avatar_hash', sa.String(length=128), nullable=True))
    op.add_column('student', sa.Column('contacts', sa.String(length=500), nullable=True))
    op.add_column('student', sa.Column('cv_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'cv_hash')
    op.drop_column('student', 'contacts')
    op.drop_column('student', 'avatar_hash')
    op.drop_column('employer', 'description')
    op.drop_column('employer', 'contacts')
    op.drop_column('employer', 'avatar_hash')
    # ### end Alembic commands ###
